server:
  port: 2002
spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wsz.springcloudalibaba.entity


logging:
  level:
    io:
      seata: info
seata:
  enabled: true
  tx-service-group: wsz_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848