server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
      - id: payment_route
#        uri: http://localhost:8001
        uri: lb://CLOUD-PAYMENT-SERVICE
        predicates:
        - Path=/payment/get/**

      - id: payment_rpote2
#        uri: http://localhost:8001
        uri: lb://CLOUD-PAYMENT-SERVICE
        predicates:
        - Path=/payment/lb/**
#        - Cookie=username,wsz
#        - Header=X-Request-Id, \d+
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

